### ISSUE TITLE
Error: Config file couldn't be found

### ISSUE THREAD

**Issue by larrymandes** [MotherRussiaS/NgrokServerStarter#1]
[21:31:42 ERROR]: [NgrokStarter] Config file couldn't be found
[21:31:42 INFO]: [NgrokStarter] null
[21:31:43 ERROR]: [NgrokStarter] JDA failed to load. Have you added your token in the config?
[21:31:43 ERROR]: Error occurred while enabling NgrokStarter v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at Main.addUsers(Main.java:177) ~[ServerStarter.jar:?]
        at Main.run(Main.java:130) ~[ServerStarter.jar:?]
        at Main.onEnable(Main.java:35) ~[ServerStarter.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:630) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1089) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

bro please add support for 1.20.2

**Comment by larrymandes** [comment]
please add support for paper

**Comment by MotherRussiaS** [comment]
Hi Larry,

I did some testing using Paper and the reason for this bug is that Paper has a folder labeled as 'config' in its server directory, which has the same name as the file used to store the plugins config.

I have created a new release which should solve your problem: [https://github.com/MotherRussiaS/NgrokServerStarter/releases/tag/v0.1.1](url)
