### ISSUE TITLE
[NgrokStarter] Config file couldn't be found

### ISSUE THREAD

**Issue by larrymandes** [MotherRussiaS/NgrokServerStarter#2]
bro the updated version behaves exactly the same. could you add support for version 1.20.2 for me, maybe it's because of her problems?

[22:21:55 INFO]: [NgrokStarter] Enabling NgrokStarter v1.0
[22:21:55 ERROR]: [NgrokStarter] Config file couldn't be found
[22:21:55 INFO]: [NgrokStarter] null
[22:21:55 ERROR]: [NgrokStarter] JDA failed to load. Have you added your token in the config?
[22:21:55 ERROR]: Error occurred while enabling NgrokStarter v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at Main.addUsers(Main.java:177) ~[2.jar:?]
        at Main.run(Main.java:130) ~[2.jar:?]
        at Main.onEnable(Main.java:35) ~[2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:630) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1089) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:21:55 INFO]: [NgrokStarter] Disabling NgrokStarter v1.0
[22:21:55 INFO]: [NgrokStarter] windows 10

**Comment by larrymandes** [comment]
the new file weighs in bytes as well as the old one

**Comment by MotherRussiaS** [comment]
Hi Larry,

I've tested the updated version using Paper 1.20.2 and everything seems to be working fine. The only thing I can suggest is for you to double check if you have downloaded

**Comment by larrymandes** [comment]
???

**Comment by MotherRussiaS** [comment]
Sorry I accidentally closed the issue, I have tested the updated version on Paper 1.20.2 and everything works fine. The only thing I can suggest is that you double check if you are using the new version.

**Comment by larrymandes** [comment]
I don't know why, but when I downloaded from releases, the old version was downloaded. now I tried again and downloaded the necessary one and everything worked, but congif.cfg is empty

**Comment by MotherRussiaS** [comment]
Good to hear, please refer to the README to setup the config.
[https://github.com/MotherRussiaS/NgrokServerStarter/blob/master/README.md](url)

You'll generally be able to copy the example file and change it as needed.

**Comment by larrymandes** [comment]
can a bot send IP addresses not to the users' personal account to the ds server?

**Comment by MotherRussiaS** [comment]
As of now no, but I would definitely be able to make this a feature in the future

**Comment by larrymandes** [comment]
configured the config but


[22:52:52 ERROR]: [NgrokStarter] JDA failed to load. Have you added your token in the config?
[22:52:52 ERROR]: Error occurred while enabling NgrokStarter v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at Main.addUsers(Main.java:177) ~[ServerStarter.jar:?]
        at Main.run(Main.java:130) ~[ServerStarter.jar:?]
        at Main.onEnable(Main.java:35) ~[ServerStarter.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[patina-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:630) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1089) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patina-1.20.2.jar:git-Patina-"809a1d2"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by larrymandes** [comment]
I have entered a token

**Comment by larrymandes** [comment]
#Token of the discord bot that you want to sent the message
token=MTI0NzI****gyNjE***G1327L.*****E8g5jI_*******GzJ3A
#Delay in ms to allow for the discord bot and ngrok to both start. Configure as needed
delay=2000
#User ids of people to send the ip to, seperated by a comma
users=644087820788563969
#A small message to add before the ip
message=Here is your ip!:
#Command that gets executed to start the ngrok client (commented by default). Use this option if your server runs on another port than 25565
#command=ngrok tcp 25565

my config

**Comment by MotherRussiaS** [comment]
I've been able to replicate your problem on my end, trying to fix it now

**Comment by MotherRussiaS** [comment]
Turns out it was an issue with commented lines, because of some laziness on my end. Ill fix it with another release at some point but in the mean time remove all the comments from your file to make it look like this:

token=your_token
delay=2000
users=644087820788563969
message=Here is your ip!:

I apologize for how unfinished this is but this is just a small side project that I spent a day doing, so bear with me.

**Comment by larrymandes** [comment]
Yes, it works now, thank you for that. I will be looking forward to updates. You are a great fellow. I wish you good luck in the future.

**Comment by MotherRussiaS** [comment]
No worries mate, thank you for being patient. I'll close this issue now.
